- paseto/config.go
- paseto/config_test.go
- paseto/helpers.go
- paseto/paseto.go
- paseto/paseto_test.go
- paseto/payload.go
As requested in #4 this PR improve some things about config and move all errors to helpers.go
- All errors are now public
- Improve default ErrorHandler error verification
- Add ContextKey and TokenLookup configs to DefaultConfig
More additions
- Replaced `Payload` struct by `paseto.JSONToken`  struct
- Fixed some typos
- Use `ConfigDefault` values when a given config is empty, to be more consistent with `ConfigDefault`
> PASETO: Replace Payload struct by paseto.JSONToken + Improve helpers and public errors

- otelfiber/fiber.go
This is to infer context from `UserContext()` instead, so the value set in `UserContext()` by users will not be simply overwritten and simply been discarded.
This PR also resolves issue #143.
---
Discussed in Discord
> Hi! I was trying to use https://github.com/gofiber/contrib/tree/v0.4.1/otelfiber and I noticed that my values set in UserContext() is not passing down. Further digging showed that at https://github.com/gofiber/contrib/blob/v0.4.1/otelfiber/fiber.go#L53-L56 the middleware just used Context() (which is of type *fasthttp.RequestCtx()) to create a new context of type context.Context and later overrides the UserContext() with that. 
>
> I think it would be more feasible for the middleware to infer context from UserContext() instead, so the value set in UserContext() will not be …
> fix: use `UserContext()` & fix incorrect strings

- fiberzap/README.md
- fiberzap/config.go
- fiberzap/zap.go
- fiberzap/zap_test.go
This PR has 2 features:
1. Supports dumping all the headers with the reqHeaders field
2. Allows to specify your own log levels in a similar way to log messages
As a bonus it speeds up the middleware as the fields are not getting marshalled if the log won't be sent to the output
> support configuring log levels and reqHeaders support

- otelfiber/config.go
- otelfiber/fiber.go
- otelfiber/fiber_test.go
- otelfiber/go.mod
- otelfiber/go.sum
- otelfiber/semconv.go
This patch adds metrics to otelfiber and follows conventions defined by [Semantic Conventions for HTTP Metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#semantic-conventions-for-http-metrics). The metric instruments are added:
- http.server.duration
- http.server.request.size
- http.server.response.size
- http.server.active_requests
The Metrics package in the OpenTelmetry-Go is still in progress. However, I believe that this PR is a good starting point for otelfiber's metrics.
Resolves #50
> feat(otelfiber): add metrics to otelfiber

- fibernewrelic/README.md
- fibernewrelic/fiber.go
- fibernewrelic/fiber_test.go
The main purpose of this PR is to fix #269 allowing the user to pass an existing `newrelic.Application`. If passed all the other config values will be ignored except for the transport type, since it's used by middleware function.
Also included:
- `TransportType` is now case insensitive. We now run ToUpper internally.
- Updated readme with example usage
- Added unit-test for testing different transport types (HTTP, HTTPS, http, invalid (defaults to HTTP))
- Added unit-test for testing against an invalid key (shorter than 40 chars)
- Added unit-test for passing a valid existing newrelic.Application
- Added unit-test for passing an invalid newrelic.Application
> Add support for passing existing New Relic application

- fiberzap/README.md
- fiberzap/config.go
- fiberzap/zap.go
- fiberzap/zap_test.go
When use compress middleware, resBody is unreadable. 
You can set GetResBody func to get readable resBody.
> Add GetResBody to Config

- fibernewrelic/README.md
- fibernewrelic/fiber.go
- fibernewrelic/fiber_test.go
It prevents creating separate transactions on NewRelic.
It groups different path params under the same route now.
Here is the NewRelic screenshot:
> change newrelic fiber to group transaction metrics under the same route

- fibernewrelic/README.md
- fibernewrelic/fiber.go
- fibernewrelic/fiber_test.go
We need to change the new relic status code when an error occurs. 
For example, if you use FiberErrorHandler and don't return a status code from the handler, you can configure a new relic status code with this MR.
> feat: add error status code handler

- otelfiber/fiber.go
- otelfiber/fiber_test.go
- otelfiber/go.mod
- otelfiber/go.sum
OpenTelemetry-Go did change the sigature for the metric.Reader interface.
They also deprecated the Unit interface in favor of a string.
To keep using otelfiber with the latest otel-go packages we need to replace the Unit struct with string constants.
I also adapted the call signature of the reader interface like it is shown in the libraries tests.
```	
metrics := metricdata.ResourceMetrics{}
err := reader.Collect(context.Background(), &metrics)
```
> Migrate to OTEL-Go v1.14.0

- jwt/config.go
- jwt/jwt_test.go
> Fix use of multi key in JWT middleware

- otelfiber/fiber.go
- otelfiber/fiber_test.go
otelcontrib.SemVersion is depracated in favour of otelcontrib.Version.
https://pkg.go.dev/go.opentelemetry.io/contrib#SemVersion
> OtelFiber: Replace deprecated SemVersion with Version

- fiberi18n/config.go
- fiberi18n/i18n.go
fix https://github.com/gofiber/contrib/issues/594
> fix(fiberi18n): use sync.Map and utils.CopyString to fix concurrent problem

- fiberzap/README.md
- fiberzap/config.go
- fiberzap/zap.go
- fiberzap/zap_test.go
> feat(fiberzap): Added 'FieldsFunc' to provide custom log fields

- swagger/README.md
- swagger/go.mod
- swagger/go.sum
- swagger/swagger.go
- swagger/swagger.yaml
- swagger/swagger_test.go
- Added support for using `YAML` as Swagger spec. Fixes #708 
- Migrated from `fasthttpadapter` to `fiber/v2/adaptor`
- Added support for `Next()`, and other missing checks
- Update documentation
- Added support for `Path` and `Title`
- Fixed bug where the middleware was reading the Spec and assuming `JSON` then passing this as `Bytes` to the `go-openapi` middleware.
- Instead now we have a `http.HandlerFunc` able to serve the SPEC based on extension type back to the middleware
- Added support for running multiple SwaggerUI's, for example:
```go
// Create Swagger middleware for v1
//
// Swagger will be available at: /api/v1/docs
app.Use(swagger.New(swagger.Config{
BasePath: "/api/v1/",
FilePath: "./docs/v1/swagger.json",
Path:     "docs",
}))
// Create Swagger middleware for v2
//
// …
```
> Refactoring and fixes to Swagger Middleware

- fiberi18n/i18n.go
https://github.com/gofiber/contrib/issues/758
`c.Locals` may take out `nil` in case of high concurrency, so it is added to prevent the program from crashing.
> fix: Increase the judgment of type strong rotation

- fiberzap/logger.go
- fiberzap/logger_test.go
Issue:
https://github.com/gofiber/contrib/issues/791
> 🩹(fiberzap) Fix incorrect log depth when use log.WithContext

- fiberzap/logger.go
In `fiberzap`, `SetOutput` warning log incorrectly refer to `SetLevel` instead of `SetOutput`
> fiberzap: Fix wrong warning message

- fiberzerolog/zerolog.go
Fix: It is impossible to use hooks that take something out of the context and write a log (example: span_id, trace_id)
> FiberZerolog: Add user context

- jwt/config.go
typo `"missing or malformed JWT"` vs `"Missing or malformed JWT"`
> fix: typo Missing vs missing

- fiberzerolog/README.md
- fiberzerolog/config.go
- fiberzerolog/zerolog_test.go
Hi, @ReneWerner87!
What do you think about it?
1) Improved request headers log:
Was:
`{"method":"POST"," header_key":"header_value"} `
Became with sub dict:
`{"method":"POST", "reqHeaders": {"header_key":"header_value"}}
`
2) Added response headers log (with field FieldResHeaders = "resHeaders"):
`{"method":"POST", "resHeaders": {"header_key":"header_value"}}`
> Improve Dict log for reqHeaders & resHeaders

- casbin/README.md
> docs: fix casbin adapter documentation url

- socketio/README.md
- socketio/socketio.go
In `socketio` package we were not able to set config for recovery explained [here](https://github.com/gofiber/contrib/tree/main/websocket#note-with-recover-middleware). In this PR I have added option to set config.
> SocketIO: Add optional websocket.Config param

- loadshed/go.mod
Problem:
```
go get github.com/gofiber/contrib/loadshed
go: github.com/gofiber/contrib/loadshed@upgrade (v0.2.0) requires github.com/gofiber/contrib/loadshed@v0.2.0: parsing go.mod:
module declares its path as: loadshed
but was required as: github.com/gofiber/contrib/loadshed
```
`module` directive contains wrong value which prevents it to be installed as a dependency
See other:
https://github.com/gofiber/contrib/blob/main/casbin/go.mod#L1
https://github.com/gofiber/contrib/blob/main/circuitbreaker/go.mod#L1
Solution:
Use correct value.
> fix(): loadshed module name;
